export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const TRAER_PRODUCTOS = "TRAER_PRODUCTOS";
export const TRAER_PRODUCTOS_EXITO = "TRAER_PRODUCTOS_EXITO";
export const TRAER_PRODUCTOS_ERROR = "TRAER_PRODUCTOS_ERROR";

export const TRAER_PRODUCTO = "TRAER_PRODUCTO";
export const TRAER_PRODUCTO_EXITO = "TRAER_PRODUCTO_EXITO";
export const TRAER_PRODUCTO_ERROR = "TRAER_PRODUCTO_ERROR";

export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTO_EXITO";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR";

export const BORRAR_PRODUCTO = "BORRAR_PRODUCTO";
export const BORRAR_PRODUCTO_EXITO = "BORRAR_PRODUCTO_EXITO";
export const BORRAR_PRODUCTO_ERROR = "BORRAR_PRODUCTO_ERROR";
